// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import (
	showall "myURLShortener/internal/http-server/handlers/url/showall"

	mock "github.com/stretchr/testify/mock"
)

// URLShower is an autogenerated mock type for the URLShower type
type URLShower struct {
	mock.Mock
}

// ShowURL provides a mock function with given fields:
func (_m *URLShower) ShowURL() ([]*showall.AliasUrl, error) {
	ret := _m.Called()

	var r0 []*showall.AliasUrl
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*showall.AliasUrl, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*showall.AliasUrl); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*showall.AliasUrl)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewURLShower interface {
	mock.TestingT
	Cleanup(func())
}

// NewURLShower creates a new instance of URLShower. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewURLShower(t mockConstructorTestingTNewURLShower) *URLShower {
	mock := &URLShower{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
